dist: trusty
language: php
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/volumio/docs.git
  - secure: joyLlj0ztDTM9fJf6G/8OV2vHynRFWKZDUEVMY1KFS3mfvffDEQUWV3CvtpsDMTzD5uExrQfC8MYE86tIpnC+glcsd2FDZ93PFvZQqwwrJuVexo82FvKyijLSYRGzMZL0AZrtek+Ds6bO8uIkgr6d1ta7/grPItJ914bdpyBow9zwsB6puWq9liDEvJH0ajmSCn6CYv+JiZneDBnJCzZoBBplEfKaGw80E6KnFyhQIyfJ7hP4VT221fympn4ztU64LdtKeYArAXwiTKdCHkEuPtTgTBfDq88nRPyFwD8umbN9eSgrFfLLqBTKgB5MiT1atMJAAaLdiCTlRT4B59BuHATJIN1hWgJ6rhmNtRxCZbWjd8rlc98H8ryfdwgfrLFLfQfgq/em6dQ7NwRrqz+nCeCzn9wa1KXXTiUulEKDJTEUhVmUugCB+liSklOnUi4MMtRpnS402iXSsmqpYKO4I+TSq4g/ElfdcfiNCoRalEpXONEHRhEHK182iVELWII4shN/PlQWb84gxy4pN0p0y+XQjvSSq+bTcKkKlhMZk0DTkIke34INzs6dw+gJ7COb9+lPmig2U/8wXfhee+fRU8UcLbdqkVLf5KxBkzr4Y/3W5x971KHABOqUXi2KbzhEWqwsIol0U22P6/QhdgqH7jd8nXS4wrSJBSVMMe0A2s=
php:
- 5.5
